# Generated by Django 6.0.2 on 2026-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_onetimecode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
