# Generated by Django 6.0.2 on 2026-03-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
